<a href="https://colab.research.google.com/github/TiffanyHizon/58101_Numerical_Methods/blob/main/Python%20Exercise%202/NM_58101_Python_Exercise_2_Hizon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Matrix and its Operations**

Create a NumPy program that performs the operations of the given matrices:
1. Sum = A + B
2. Difference1 = B - A
3. Difference2 = A - B

$$A = \begin{bmatrix} -5&0\\4&1 \\\end{bmatrix} , B = \begin{bmatrix} 6 & 3 \\ 2 & 3 \end{bmatrix} $$

In [1]:
import numpy as np

In [2]:
A = np.array([
              [-5, 0],
              [4, 1]
              ])
B = np.array([
              [6, -3],
              [2, 3]
              ])

**Addition**

In [3]:
#Eager Execution

Sum = A + B
Sum

array([[ 1, -3],
       [ 6,  4]])

In [4]:
#Functional Method

Sum = np.add(A, B)
Sum

array([[ 1, -3],
       [ 6,  4]])

**Subtraction - Difference 1**

In [5]:
#Eager Execution

Difference1 = B - A
Difference1

array([[11, -3],
       [-2,  2]])

In [6]:
#Functional Method

Difference1 = np.subtract(B, A)
Difference1

array([[11, -3],
       [-2,  2]])

**Subtraction - Difference 2**


In [7]:
#Eager Execution

Difference2 = A - B
Difference2

array([[-11,   3],
       [  2,  -2]])

In [8]:
#Functional Method

Difference2 = np.subtract(A, B)
Difference2

array([[-11,   3],
       [  2,  -2]])