<a href="https://colab.research.google.com/github/TiffanyHizon/58101_Numerical_Methods/blob/main/Matrix%20Algebra/NM_58101_Matrix_Algebra_Hizon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix and Its Operation

In [9]:
import numpy as np

In [16]:
a = np.array([1, 2, 3]) #An example of (1 x 3) array
a.shape

(3,)

In [21]:
b = np.array([[1, 2, 3], 
             [4, 5, 6]
             ])
print("Matrix b: ", b)
print("Shape: ", b.shape)
b[0, 0] = 7
b

Matrix b:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)


array([[7, 2, 3],
       [4, 5, 6]])

In [22]:
c = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
d = np.full((1, 2), 7)
d

array([[7, 7]])

In [27]:
e = np.eye(2, 2)
e

array([[1., 0.],
       [0., 1.]])

In [30]:
#using the values in matrix c

f = np.diagonal(c)
print("Values: ", c)
f

Values:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [35]:
g = np.zeros([2, 2])
g

array([[0., 0.],
       [0., 0.]])

In [37]:
#using matrix e and g

add = np.add(e, g)
add

array([[1., 0.],
       [0., 1.]])

In [39]:
subtract = np.subtract(e, g)
subtract

array([[1., 0.],
       [0., 1.]])